GENERAL_USER_INDEX = 'general-user'
DOCTOR_INDEX = 'doctor'
POST_INDEX = 'post'
DOCTOR_ACTIVATION_INDEX = 'doctor-activation'
FORGOT_PASSWORD_TOKEN_INDEX = 'forgot-password-token'
UTC_PATTERN = "\+(?P<hour>\d{2}):(?P<minute>\d{2})$"
UTC_REPL = "+\g<hour>\g<minute>"
UTC_REGEX = "%Y-%m-%dT%H:%M:%S.%f%z"
UTF_8 = 'utf-8'
HOME_HTML_PATH = 'smfhcp/home.html'
TRENDING_HTML_PATH = 'smfhcp/trending.html'
STATUS_404_HTML_PATH = 'smfhcp/404.html'
STATUS_500_HTML_PATH = 'smfhcp/500.html'
LOGIN_HTML_PATH = 'registrations/login.html'
APPLICATION_JSON_TYPE = "application/json"
REGISTER_THROUGH_EMAIL_HTML_PATH = 'smfhcp/register_through_email.html'
DOCTOR_CREATE_PROFILE_HTML_PATH = 'smfhcp/doctor_create_profile.html'
RESET_PASSWORD_EMAIL_HTML_PATH = 'smfhcp/reset_password_email.html'
RESET_PASSWORD_HTML_PATH = 'smfhcp/reset_password.html'
VIEW_PROFILE_HTML_PATH = 'smfhcp/view_profile.html'
VIEW_POST_HTML_PATH = 'smfhcp/view_post.html'
SEARCH_QUERY_JSON = 'smfhcp/search_query.json'
TAGGED_HTML_PATH = 'smfhcp/tagged.html'
SEARCH_HTML_PATH = 'smfhcp/search.html'
USER_OR_EMAIL_ALREADY_EXISTS_MESSAGE = 'User name or email already exists.'
USERNAME_AND_PASSWORD_DO_NOT_MATCH = 'Username/Password does not match.'
USER_ALREADY_EXISTS = "User already exists."
USER_ALREADY_INVITED = "User already invited."
SENT_INVITE = "Sent Invite"
INVITE_EMAIL_SUBJECT = "Invitation to join SMFHCP as a Health care Professional"
COULD_NOT_SEND_EMAIL = 'Could not send email.'
INVITATION_SENT_SUCCESSFULLY = 'Invitation sent successfully.'
USERNAME_ALREADY_EXISTS = 'Username already exists.'
EMAIL_DOES_NOT_HAVE_INVITE = 'This email id does not have an invite.'
OTP_EMAIL_PAIR_DOES_NOT_MATCH = 'OTP, email pair do not match.'
PASSWORD_RESET_REQUEST_SUBJECT = 'Password reset request for SMFHCP'
DEFAULT_PROFILE_PICTURE = '/static/images/profiles/default.jpg'
PROFILE_PICTURE_PATH_BASE = '/static/images/profiles/'
